name: Deploy to S3 bucket

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Initial checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Print working directory
        run: pwd
        
      - name: Build & push docker image
        run: |
          
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/project-nginx:${{ github.run_number }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/project-nginx:${{ github.run_number }}
          docker save ${{ secrets.DOCKER_USERNAME }}/project-nginx:${{ github.run_number }} -o project-nginx.tar
      
      # folosim metoda asta ca ma loghez ca IAM user 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure: us-east-1 
      
      # folosim metoda asta ca ma loghez cu IAM role (adica sunt logat ca si IAM user si ma duc sa imi creez un IAM role si ii dau permisiuni)
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #  with:
      #    role-to-assume: arn:aws:iam::<AWS-account-ID>:role/bogdan-github-actions-role-s3
      #    aws-region: us-east-1
      
      - name: Push Docker image to AWS S3
        run: |
          aws s3 cp project-nginx.tar s3://project-bucket-softbinator/project-nginx.tar
        
  deploy:
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
      - name: Start the docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker container rm -f container-nginx-from-s3
            aws s3 cp s3://project-bucket-softbinator/project-nginx.tar project-nginx.tar
            docker load -i project-nginx.tar 
            #docker tag  bogdanapostol97/project-nginx:16 project-nginx:16  
            docker image ls
            docker run -d -p 80:80 --name container-nginx-from-s3 --env Port=80 bogdanapostol97/project-nginx:17
