name: Deploy to S3 bucket

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Initial checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Vreau sa stiu care este work directory in caz ca imi trebuie
      - name: Print working directory
        run: pwd

      # Ultima comanda salveaza imaginea intr-un tar
      - name: Build & push docker image
        run: |
          
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/project-nginx:${{ github.run_number }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/project-nginx:${{ github.run_number }}
          docker save ${{ secrets.DOCKER_USERNAME }}/project-nginx:${{ github.run_number }} -o project-nginx.tar
 
      # Instalez pe Runner AWS CLI Tools sa ma pot conecta apoi la contul de AWS
      - name: Install AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade --user
      
      # Configurez contul de AWS si ma conectez la el [ Pune regiunea pe care tu o folosesti ca default]
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: |
            aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region us-east-1 
      
      # Fac push la arhiva unde este imaginea mea in S3-ul meu
      - name: Push Docker image to AWS S3
        run: |
          aws s3 cp project-nginx.tar s3://project-bucket-softbinator/project-nginx.tar
        
  deploy:
    runs-on: ubuntu-22.04
    needs: [build]
    steps:

      # Instalez pe Runner AWS CLI Tools sa ma pot conecta apoi la contul de AWS
      - name: Install AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade --user
      
      # Configurez contul de AWS si ma conectez la el [ Pune regiunea pe care tu o folosesti ca default]
      - name: Configure AWS credentials
        env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1 

      # Download la imagine din S3 [acesta este un runner nou deci nu este srtat ca primul asa ca trebuie iar setat]
      - name: Download Docker image from AWS S3
        run: |
          aws s3 cp s3:/project-bucket-softbinator/project-nginx.tar project-nginx.tar
          docker load -i project-message.tar

      # Fa deploy folosind imaginea din S3
      - name: Start the docker container
        uses: appleboy/ssh-action@master
        with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker container rm -f unruffled_levitt
          docker run -d
          -p 80:80
          --name container-nginx-from-s3
          --env Port=8080 project-bucket-softbinator/project-nginx:${{ github.run_number }}
